### ISSUE TITLE
When .otio file contains a segment of an audio clip that does not start at 0, the audio plays too far into the next clip.

### ISSUE THREAD

**Issue by ggarra13** [darbyjohnston/tlRender#107]
I sent you privately a file that is hard to hear the issue.  Here's another one with 23.976 FPS with the default clips.  The tramway's sound of the first clip can be heard into the second clip (even though it has no sound).

[audio_far.otio.txt](https://github.com/darbyjohnston/tlRender/files/12507367/audio_far.otio.txt)

**Comment by darbyjohnston** [comment]
This should be fixed now in the "edit" branch, hopefully along with the other audio issues.
