### ISSUE TITLE
Qt version does not display video

### ISSUE THREAD

**Issue by freder** [darbyjohnston/tlRender#109]
hi,

I built the Qt6 version successfully, but it only shows _black_
(OpenGL Version renders the video fine.)

<img width="1305" alt="Screenshot 2023-09-13 at 12 31 52" src="https://github.com/darbyjohnston/tlRender/assets/724844/42a9548d-822d-4700-9ff6-057e7167a22a">

- macOS `13.5.2`
- Qt installed via `homebrew`

---

Also `cmd-q` does not quit the app

**Comment by darbyjohnston** [comment]
Hi, I checked a fix for this into the "main" branch. If you have a chance try syncing to the latest and rebuilding, you will also need to reset the settings. To reset the settings from the command line:

```tlplay-qt -resetSettings```

To reset the settings from the UI check out the attached screenshot; open the settings panel and click the "Default Settings" button. You will then need to restart the application.

![tlRender Settings 2023-09-13](https://github.com/darbyjohnston/tlRender/assets/8532558/1d27f127-26d7-4343-ac3b-9444d49a04b7)

I'm not sure what's going on with the quit command, it seems to work OK in Qt5. I wonder if it has to do with starting a UI application from the command line.
