### ISSUE TITLE
Bad sequence detection.

### ISSUE THREAD

**Issue by ggarra13** [darbyjohnston/tlRender#115]
Find an attached file with two files.  When read into tlRender, they are incorrectly determined to be a sequence and tlRender tries to load frame 0.

[bad_sequence.zip](https://github.com/darbyjohnston/tlRender/files/12713837/bad_sequence.zip)

**Comment by ggarra13** [comment]
Fixed in PR #117,

**Comment by darbyjohnston** [comment]
Thanks for pointing this out, I just checked in a change to the "edit" branch that should fix this.
