### ISSUE TITLE
Add a std::future/std::promise to send I/O options to tlIO 

### ISSUE THREAD

**Issue by ggarra13** [darbyjohnston/tlRender#118]
Currently, there's some modules that would benefit from a mechanism to send a std::map<std::string, std::string> (ioOptions?) of options to tlIO.  For example, the USD reader has all sets of parameters to control its visualization that now are sent only on start up.  Changing them means re-loading the file to take effect.
Any thoughts on this, Darby?

**Comment by darbyjohnston** [comment]
This could be useful though there may be some options that only apply when opening the file, I guess they could either be ignored or the file closed and re-opened. Maybe in addition to passing the options to the constructor they could also be passed to the ```readVideo``` and ```readAudio``` functions.

However I just realized there is a bug with the options, the I/O cache does not take them into account which means they will be ignored if the requested image is already in the cache. I need to fix this first...

**Comment by darbyjohnston** [comment]
I fixed the bug with the cache and added the option arguments to ```readVideo``` and ```readAudio```. Note the options passed to those functions are merged with the options passed when constructing the reader. Currently only the USD plugin is using the new functionality, I added some UI to "tlplay-gl" and "tlplay-qt" for testing it out and it seems to be working OK:

![tlRender USD Options 2023-10-14](https://github.com/darbyjohnston/tlRender/assets/8532558/cbbb7ace-a7a6-49c2-b71d-4c3bd727fdfc)

**Comment by ggarra13** [comment]
I also added this to mrv2.  You are also using the options in the EXR reader to read the layer.
