### ISSUE TITLE
Small? movies seem to display black

### ISSUE THREAD

**Issue by ggarra13** [darbyjohnston/tlRender#42]
BART_2021-02-07.m4v, PSR63_2012-06-02.mov and Dinky_2015-06-11.m4v display black on all players (linux tested only), at least on this commit:

d4f302f9666e4a5109701db16e2e3398d4239bbd

**Comment by darbyjohnston** [comment]
Could you add the "-log" command line flag and attach or send me the output? As I mentioned over email, those are the movies I test with and have never seen any issues with them.

**Comment by ggarra13** [comment]
4.1 ATI-4.8.101
4.1.0

Keyboard shortcuts:

    Escape - Exit
    U      - Fullscreen mode
    H      - HUD enabled
    Space  - Start/stop playback
    L      - Loop playback
    Home   - Go to the start time
    End    - Go to the end time
    Left   - Go to the previous frame
    Right  - Go to the next frame

[LOG] 0.00 tl::system::Context: 
    System: Darwin 21.6.0 x86_64
    Cores:  16
    RAM:    16GB
[LOG] 0.00 tl::audio::System: Create
[LOG] 0.00 tl::audio::System: RtAudio version: 5.1.0
[LOG] 0.00 tl::audio::System: Audio API: CoreAudio
[LOG] 0.04 tl::audio::System: 
    Device 0: Apple Inc.: MacBook Pro (micr—fono)
        Channels: 0 output, 1 input, 0 duplex
        Sample rates: 44100 48000 88200 96000 
        Preferred sample rate: 48000
        Native formats: F32 
    Device 1: Apple Inc.: MacBook Pro (bocinas)
        Channels: 2 output, 0 input, 0 duplex
        Sample rates: 44100 48000 88200 96000 
        Preferred sample rate: 48000
        Native formats: F32 
    Device 2: zoom.us: ZoomAudioDevice
        Channels: 2 output, 2 input, 2 duplex
        Sample rates: 48000 
        Preferred sample rate: 48000
        Native formats: F32 
    Default input device: 0
    Default input info: 1 F32 48000
    Default output device: 1
    Default output info: 2 F32 48000
[LOG] 0.04 tl::io::System: Create
[LOG] 0.04 tl::io::ffmpeg::Plugin: Codecs: a64multi, a64multi5, alias_pix, amv, apng, asv1, asv2, avrp, avui, ayuv, bitpacked, bmp, cfhd, cinepak, cljr, comfortnoise, dnxhd, dpx, dvvideo, exr, ffv1, ffvhuff, fits, flashsv, flashsv2, flv, gif, h261, h263, h263p, huffyuv, jpeg2000, jpegls, ljpeg, magicyuv, mjpeg, mpeg1video, mpeg2video, mpeg4, msmpeg4v2, msmpeg4, msvideo1, pam, pbm, pcx, pfm, pgm, pgmyuv, phm, png, ppm, prores, prores_aw, prores_ks, qoi, qtrle, r10k, r210, rawvideo, roqvideo, rpza, rv10, rv20, s302m, sgi, smc, snow, speedhq, sunrast, svq1, targa, tiff, utvideo, v210, v308, v408, v410, vbn, vc2, wbmp, wrapped_avframe, wmv1, wmv2, xbm, xface, xwd, y41p, yuv4, zlib, zmbv, aac, ac3, ac3_fixed, alac, aptx, aptx_hd, dca, dfpwm, eac3, flac, g723_1, hdr, mlp, mp2, mp2fixed, nellymoser, opus, real_144, sbc, sonic, sonicls, truehd, tta, vorbis, wavpack, wmav1, wmav2, pcm_alaw, pcm_bluray, pcm_dvd, pcm_f32be, pcm_f32le, pcm_f64be, pcm_f64le, pcm_mulaw, pcm_s8, pcm_s8_planar, pcm_s16be, pcm_s16be_planar, pcm_s16le, pcm_s16le_planar, pcm_s24be, pcm_s24daud, pcm_s24le, pcm_s24le_planar, pcm_s32be, pcm_s32le, pcm_s32le_planar, pcm_s64be, pcm_s64le, pcm_u8, pcm_u16be, pcm_u16le, pcm_u24be, pcm_u24le, pcm_u32be, pcm_u32le, pcm_vidc, roq_dpcm, adpcm_adx, adpcm_argo, g722, g726, g726le, adpcm_ima_amv, adpcm_ima_alp, adpcm_ima_apm, adpcm_ima_qt, adpcm_ima_ssi, adpcm_ima_wav, adpcm_ima_ws, adpcm_ms, adpcm_swf, adpcm_yamaha, ssa, ass, dvbsub, dvdsub, mov_text, srt, subrip, text, ttml, webvtt, xsub, aac_at, alac_at, ilbc_at, pcm_alaw_at, pcm_mulaw_at, libmp3lame, libopus, libtheora, libvorbis, libvpx, libvpx-vp9, libwebp_anim, libwebp, libx264, libx264rgb, libx265, h264_videotoolbox, hevc_videotoolbox, prores_videotoolbox, aasc, aic, alias_pix, agm, amv, anm, ansi, apng, arbc, argo, asv1, asv2, aura, aura2, avrp, avrn, avs, avui, ayuv, bethsoftvid, bfi, binkvideo, bitpacked, bmp, bmv_video, brender_pix, c93, cavs, cdgraphics, cdtoons, cdxl, cfhd, cinepak, clearvideo, cljr, cllc, comfortnoise, cpia, cri, camstudio, cyuv, dds, dfa, dirac, dnxhd, dpx, dsicinvideo, dvaudio, dvvideo, dxa, dxtory, dxv, eacmv, eamad, eatgq, eatgv, eatqi, 8bps, 8svx_exp, 8svx_fib, escape124, escape130, exr, ffv1, ffvhuff, fic, fits, flashsv, flashsv2, flic, flv, fmvc, 4xm, fraps, frwu, g2m, gdv, gem, gif, h261, h263, h263i, h263p, h264, hap, hevc, hnm4video, hq_hqa, hqx, huffyuv, hymt, idcinvideo, iff, imm4, imm5, indeo2, indeo3, indeo4, indeo5, interplayvideo, ipu, jpeg2000, jpegls, jv, kgv1, kmvc, lagarith, loco, lscr, m101, magicyuv, mdec, mimic, mjpeg, mjpegb, mmvideo, mobiclip, motionpixels, mpeg1video, mpeg2video, mpeg4, mpegvideo, msa1, mscc, msmpeg4v1, msmpeg4v2, msmpeg4, msp2, msrle, mss1, mss2, msvideo1, mszh, mts2, mv30, mvc1, mvc2, mvdv, mvha, mwsc, mxpeg, notchlc, nuv, paf_video, pam, pbm, pcx, pfm, pgm, pgmyuv, pgx, phm, photocd, pictor, pixlet, png, ppm, prores, prosumer, psd, ptx, qdraw, qoi, qpeg, qtrle, r10k, r210, rasc, rawvideo, rl2, roqvideo, rpza, rscc, rv10, rv20, rv30, rv40, s302m, sanm, scpr, screenpresso, sga, sgi, sgirle, sheervideo, simbiosis_imx, smackvid, smc, smvjpeg, snow, sp5x, speedhq, speex, srgc, sunrast, svq1, svq3, targa, targa_y216, tdsc, theora, thp, tiertexseqvideo, tiff, tmv, truemotion1, truemotion2, truemotion2rt, camtasia, tscc2, txd, ultimotion, utvideo, v210, v210x, v308, v408, v410, vb, vbn, vble, vc1, vc1image, vcr1, vmdvideo, vmnc, vp3, vp4, vp5, vp6, vp6a, vp6f, vp7, vp8, vp9, vqavideo, wbmp, webp, wcmv, wrapped_avframe, wmv1, wmv2, wmv3, wmv3image, wnv1, xan_wc3, xan_wc4, xbm, xface, xl, xpm, xwd, y41p, ylc, yop, yuv4, 012v, zerocodec, zlib, zmbv, aac, aac_fixed, aac_latm, ac3, ac3_fixed, acelp.kelvin, alac, als, amrnb, amrwb, ape, aptx, aptx_hd, atrac1, atrac3, atrac3al, atrac3plus, atrac3plusal, atrac9, binkaudio_dct, binkaudio_rdft, bmv_audio, cook, dca, dfpwm, dolby_e, dsd_lsbf, dsd_msbf, dsd_lsbf_planar, dsd_msbf_planar, dsicinaudio, dss_sp, dst, eac3, evrc, fastaudio, wavesynth, flac, g723_1, g729, gsm, gsm_ms, hca, hcom, hdr, iac, ilbc, imc, interplayacm, mace3, mace6, metasound, mlp, mp1, mp1float, mp2, mp2float, mp3float, mp3, mp3adufloat, mp3adu, mp3on4float, mp3on4, mpc7, mpc8, msnsiren, nellymoser, on2avc, opus, paf_audio, qcelp, qdm2, qdmc, real_144, real_288, ralf, sbc, shorten, sipr, siren, smackaud, sonic, tak, truehd, truespeech, tta, twinvq, vmdaudio, vorbis, wavpack, wmalossless, wmapro, wmav1, wmav2, wmavoice, ws_snd1, xma1, xma2, pcm_alaw, pcm_bluray, pcm_dvd, pcm_f16le, pcm_f24le, pcm_f32be, pcm_f32le, pcm_f64be, pcm_f64le, pcm_lxf, pcm_mulaw, pcm_s8, pcm_s8_planar, pcm_s16be, pcm_s16be_planar, pcm_s16le, pcm_s16le_planar, pcm_s24be, pcm_s24daud, pcm_s24le, pcm_s24le_planar, pcm_s32be, pcm_s32le, pcm_s32le_planar, pcm_s64be, pcm_s64le, pcm_sga, pcm_u8, pcm_u16be, pcm_u16le, pcm_u24be, pcm_u24le, pcm_u32be, pcm_u32le, pcm_vidc, derf_dpcm, gremlin_dpcm, interplay_dpcm, roq_dpcm, sdx2_dpcm, sol_dpcm, xan_dpcm, adpcm_4xm, adpcm_adx, adpcm_afc, adpcm_agm, adpcm_aica, adpcm_argo, adpcm_ct, adpcm_dtk, adpcm_ea, adpcm_ea_maxis_xa, adpcm_ea_r1, adpcm_ea_r2, adpcm_ea_r3, adpcm_ea_xas, g722, g726, g726le, adpcm_ima_acorn, adpcm_ima_amv, adpcm_ima_alp, adpcm_ima_apc, adpcm_ima_apm, adpcm_ima_cunning, adpcm_ima_dat4, adpcm_ima_dk3, adpcm_ima_dk4, adpcm_ima_ea_eacs, adpcm_ima_ea_sead, adpcm_ima_iss, adpcm_ima_moflex, adpcm_ima_mtf, adpcm_ima_oki, adpcm_ima_qt, adpcm_ima_rad, adpcm_ima_ssi, adpcm_ima_smjpeg, adpcm_ima_wav, adpcm_ima_ws, adpcm_ms, adpcm_mtaf, adpcm_psx, adpcm_sbpro_2, adpcm_sbpro_3, adpcm_sbpro_4, adpcm_swf, adpcm_thp, adpcm_thp_le, adpcm_vima, adpcm_xa, adpcm_yamaha, adpcm_zork, ssa, ass, cc_dec, dvbsub, dvdsub, jacosub, microdvd, mov_text, mpl2, pgssub, pjs, realtext, sami, srt, stl, subrip, subviewer, subviewer1, text, vplayer, webvtt, xsub, aac_at, ac3_at, adpcm_ima_qt_at, alac_at, amr_nb_at, eac3_at, gsm_ms_at, ilbc_at, mp1_at, mp2_at, mp3_at, pcm_alaw_at, pcm_mulaw_at, qdmc_at, qdm2_at, libopus, libvorbis, libvpx, libvpx-vp9, bintext, xbin, idf, av1
[LOG] 0.05 tl::io::ffmpeg::Plugin: Reinit context to 320x192, pix_fmt: yuv420p
[LOG] 0.05 tl::io::ffmpeg::Plugin: Reinit context to 320x192, pix_fmt: yuv420p
[LOG] 0.06 tl::io::ffmpeg::Plugin: Statistics: 91957 bytes read, 2 seeks
[LOG] 0.06 tl::io::ffmpeg::Plugin: Statistics: 91957 bytes read, 2 seeks
[LOG] 0.06 tl::timeline::Timeline: 
    Create from path: ../etc/SampleData/BART_2021-02-07.m4v
    Audio path: 
[LOG] 0.07 tl::timeline::Timeline 0x600000f185c0: 
    File sequence audio: BaseName
    File sequence audio file name: 
    File sequence audio directory: 
    Video request count: 16
    Audio request count: 16
    Request timeout: 5ms
    AV I/O ffmpeg/AudioChannelCount: 2
    AV I/O ffmpeg/AudioDataType: F32
    AV I/O ffmpeg/AudioSampleRate: 48000
    Path max number digits: 9
[LOG] 0.07 tl::io::ffmpeg::Read (/Users/gga/code/lib/tlRender/lib/tlIO/FFmpegRead.cpp: 177): ../etc/SampleData/../etc/SampleData/BART_2021-02-07.m4v: ../etc/SampleData/../etc/SampleData/BART_2021-02-07.m4v: No such file or directory
[LOG] 0.07 tl::io::ffmpeg::Read (/Users/gga/code/lib/tlRender/lib/tlIO/FFmpegRead.cpp: 177): ../etc/SampleData/../etc/SampleData/BART_2021-02-07.m4v: ../etc/SampleData/../etc/SampleData/BART_2021-02-07.m4v: No such file or directory
[LOG] 0.07 tl::timeline::Timeline 0x600000f185c0: 
    Duration: 704.000000/30.000000
    Global start time: 0.000000/30.000000
    Video: 0x0 None
    Audio: 0 None 0
[LOG] 0.07 tl::timeline::TimelinePlayer 0x600000f0eea0: 
    Cache read ahead: 4.000000/1.000000
    Cache read behind: 0.500000/1.000000
    Timer mode: System
    Audio buffer frame count: 256
    Mute timeout: 500ms
    Sleep timeout: 5ms
[LOG] 0.07 play-glfw: GLFW version: 3.3.8
[LOG] 1.64 play-glfw: OpenGL version: 4.1.0
[LOG] 1.71 tl::gl::Render: Creating shader



> El 17 ago. 2022, a las 14:04, Darby Johnston ***@***.***> escribió:
> 
> 
> Could you add the "-log" command line flag and attach or send me the output? As I mentioned over email, those are the movies I test with and have never seen any issues with them.

Okay, I put the log and it pointed out the problem: relative paths.  Here’s the command and attached the log:

$ play-glfw -log ../etc/SampleData/BART_2021-02-07.m4v 



—
Gonzalo Garramuno
***@***.***
