### ISSUE TITLE
Compiling libtiff with deflate support leads to undefined references

### ISSUE THREAD

**Issue by ggarra13** [darbyjohnston/tlRender#46]
When libdeflate.a (or libdeflate.so) is found in one of the library dirs, compilation of the example programs fails with errors like:

 tif_zip.c:(.text+0xfe): undefined reference to `libdeflate_free_decompressor'

The quick fix is to add:

-Dlibdeflate=OFF to the CMAKE_ARGS of BuildTIFF.cmake.

A better fix would be to include the deflate library in the linking phase, albeit I was unable to find where:

find_package(Deflate)

is found to see what library variable it sets.

**Comment by darbyjohnston** [comment]
Is this the library?
https://github.com/ebiggers/libdeflate

I am very hesitant to add anymore dependencies, especially if they don't have CMake support.

**Comment by ggarra13** [comment]
> El 19 ago. 2022, a las 13:12, Darby Johnston ***@***.***> escribió:
> 
> 
> Is this the library?
> https://github.com/ebiggers/libdeflate
> 
> I am very hesitant to add anymore dependencies, especially if they don't have CMake support.
> 

Yes, that’s it.  The library dependency is not to be added.  It comes by default on Ubuntu 22.04.1.  BuildLibZ.cmake will detect it and the compilation will fail if the flag is not set.

—
Gonzalo Garramuno
***@***.***

**Comment by ggarra13** [comment]
Sorry.  I meant BuildTIFF.cmake the one that finds Deflate.

**Comment by darbyjohnston** [comment]
I changed the TIFF build script to add "-Dlibdeflate=OFF".
