### ISSUE TITLE
Add support for rendering to files

### ISSUE THREAD

**Issue by darbyjohnston** [darbyjohnston/tlRender#6]
Add a new application, maybe "tlrbake", that can read an .otio file and turn it into a movie.

**Comment by jhodges10** [comment]
Would love to see support for output to a multitude of formats:
- h.264
- h.265
- DNxHD
- ProRes (obviously the hardest...)

**Comment by darbyjohnston** [comment]
It looks like FFmpeg supports encoding to ProRes:
https://trac.ffmpeg.org/wiki/Encode/VFX

Though for official support we would need to implement an I/O plugin for macOS AVFoundation/CoreVideo.

**Comment by jhodges10** [comment]
I just added image sequences to my list, I can think of some situations in which you'd want that for something downstream.

**Comment by darbyjohnston** [comment]
I've added a command-line application that can render a timeline to a movie file or image file sequence; some examples:

Convert a timeline to a movie file:
```tlrbake timeline.otio output.mp4```

Convert a timeline to a low-resolution movie file:
```tlrbake timeline.otio output.mp4 -rs 640x360```

Convert a timeline to a ProRes movie file:
```tlrbake timeline.otio output.mov -vc prores```

Convert a timeline to a TIFF image sequence:
```tlrbake timeline.otio output.1.tif```

It is pretty basic and missing lots of functionality, but seems to work well enough to start testing it. I've successfully created H264 and ProRes files, the H265 and DNxHD need more work and just throw errors right now. Supported image sequences are currently OpenEXR, JPEG, PNG, and TIFF.

**Comment by jhodges10** [comment]
Nice work @darbyjohnston!

**Comment by darbyjohnston** [comment]
I need to write some proper documentation, but until then here are a couple more features:
* Support for Cineon and DPX image sequences (just regular 10-bit files for now)
* Support for OpenColorIO color space conversion
* More options for ProRes output

For example here is how to convert a .otio file that references a DPX image sequence to a color-corrected H264 movie:
```
tlrbake-glfw dpx_sequence.otio output.m4v -colorConfig spi-vfx\config.ocio -colorInput lg10 -colorDisplay sRGB -colorView Film
```

Or a high quality ProRes movie:
```
tlrbake-glfw dpx_sequence.otio output.mov -ffProfile ProRes_XQ -colorConfig spi-vfx\config.ocio -colorInput lg10 -colorDisplay sRGB -colorView Film
```

**Comment by jhodges10** [comment]
Can't wait to test out this build. Nice work as always!

**Comment by darbyjohnston** [comment]
The two remaining pieces of work are adding audio support (https://github.com/darbyjohnston/tlRender/issues/25) and creating release packages (https://github.com/darbyjohnston/tlRender/issues/8). I've created separate issues for those so I'm going to close this one.
