### ISSUE TITLE
Linux playback with a cache of several seconds does not update sometimes

### ISSUE THREAD

**Issue by ggarra13** [darbyjohnston/tlRender#88]
I am seeing an issue on Linux (Windows on the same machine is fine) where the cache has data, yet there's a stutter during playbacks.  Looking into the code, the FLTK timeouts are being called properly, but the currentVideoObserver in TimelinePlayer.cpp is not getting called sometimes, skipping several frames even.  The cache line shows the buffer is full, so that's not it.  Maybe the thread reading code is blocking?
This is with a merged scene branch and with the SolLevante movie (other movies are fine).

**Comment by ggarra13** [comment]
Also, I should mention that on Linux, with SolLevante, the default settings of Read Ahead 4.0 and Read Behind 0.5 seem to work better than, say, a cache of R.A. 10.0 and R.B. 2 even though I have more memory and the playback starts with a bigger cache.
On Windows,, I don't see that behavior.  The cache behaves properly.

**Comment by darbyjohnston** [comment]
Just checking that you are building in "Release" mode? At least on Windows the "Debug" mode can have significant overhead from the standard library.

I tried profiling the code a bit and made a couple small optimizations. Probably not enough but you might try the latest code from the "scene" branch to see if it helps. One of the optimizations was to delay the cache updates a bit, so you will notice a small lag in the cache display on the timeline.

Also have you checked the system monitor to make sure that you are not using too much memory? If you exceed the system memory that will definitely cause freezes.

**Comment by ggarra13** [comment]
Yes, I was compiling Release.

I think I found out what it was.  It was a disk issue as I suspected.  The movies was in an NTFS non-SSD drive.  It seems windows, as NTFS is native to it, reads it just fine, while the ntfs-3g driver of Linux is not as good.

Once I moved the SolLevante movie to a SSD drive (the one where Windows was installed), everything played smoothly.

**Comment by jhodges10** [comment]
I believe the ntfs-3g driver has a pretty low read speed based on my experience with it in the past. This [Stackoverflow post](https://superuser.com/questions/613869/ntfs-write-speed-really-slow-15mb-s-on-ubuntu) has some good recommendations though.
