### ISSUE TITLE
Add an option for clearing the cache

### ISSUE THREAD

**Issue by darbyjohnston** [darbyjohnston/tlRender#98]

**Comment by ggarra13** [comment]
Currently in the edit branch.  Seems to work fine.

**Comment by ggarra13** [comment]
It could be ideal if it were also an option to refresh a single frame of the cache, to load a single image that was just rendered, instead of clearing __all__ the cache.

**Comment by darbyjohnston** [comment]
I added a separate issue for that:
https://github.com/darbyjohnston/tlRender/issues/119
